### ISSUE TITLE
KeyError: 'commands' from ACTIVATION_URL

### ISSUE THREAD

**Issue by damascene** [smk762/pytomicDEX_makerbot#12]
```
# ./makerbot.py 

Traceback (most recent call last):
  File "/app/pytomicDEX_makerbot/const.py", line 66, in <module>
    ACTIVATE_COMMANDS = requests.get(ACTIVATION_URL).json()["commands"]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'commands'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pytomicDEX_makerbot/./makerbot.py", line 4, in <module>
    from helpers import (
  File "/app/pytomicDEX_makerbot/helpers.py", line 10, in <module>
    from const import ACTIVATE_COMMANDS, PRICES_URL, OP_SYS, SCRIPT_PATH
  File "/app/pytomicDEX_makerbot/const.py", line 76, in <module>
    f"Unable to load {ACTIVATE_COMMANDS}, please check your internet connection, or report this to smk on Discord."

```

Is that the Activation URL doesn't provide `commadns` anymore? 

https://github.com/smk762/pytomicDEX_makerbot/blob/6cf103cb7cdf9b450a8f411389c41f165e5b91d0/const.py#L59

**Comment by smk762** [comment]
Thanks - I've replaced this with local activation command building. It uses task based methods, so there is some lag, but any disabled coins in makerbot config should init activation on bot launch.

Tokens are not currently handled, but I"ll add that later this week.

**Comment by ShorelineCrypto** [comment]
Any progress to upgrade this PR to migrate into Gleec?  The bot USDT-PLG20 or USDC-PLG20 no longer works well on adex-microbot, which I believe because the proxy and rpc URL change on MATIC tokens on this repo activation URL.
