### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by damascene** [smk762/pytomicDEX_makerbot#4]
It accepted me not entering a value for `bot_refresh_rate` but then showed an error at the end. Maybe should not allow me to proceed or have a default value.

```
MM2.json file created.
Be sure to make a secure backup of your seed phrase offline!
userpass file created.
coins file not found, downloading...

First we need to set up some configs...

Don't forget to evaluate your risk tolerance and only trade small amounts you are comfortable with.
Enter tickers of coins you want to sell, seperated by a space:
XRG BCH KMD  
Enter tickers of coins you want to buy, seperated by a space:
XRG BCH KMD
Enter default minimum trade value in USD (e.g. 10): 5
Enter default maximum trade value in USD (e.g. 100): 500
Enter default spread percentage (e.g. 5): 1
How often to update prices in seconds (e.g. 180): 
{
    "sell_coins": [
        "KMD",
        "XRG",
        "BCH"
    ],
    "buy_coins": [
        "KMD",
        "XRG",
        "BCH"
    ],
    "default_min_usd": 5,
    "default_max_usd": 500,
    "default_spread": 1.01,
    "refresh_rate": "",
    "prices_api": "https://prices.cipig.net:1717/api/v2/tickers?expire_at=600",
    "prices_api_timeout": 180,
    "use_bidirectional_threshold": true
}
Confirm configuration? [Y/N]: Y
Traceback (most recent call last):
  File "/home/top/dev/trading/pytomicDEX_makerbot/./makerbot.py", line 2, in <module>
    from lib_atomicdex import *
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_atomicdex.py", line 3, in <module>
    from lib_helper import *
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_helper.py", line 2, in <module>
    from lib_const import *
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_const.py", line 321, in <module>
    get_makerbot_settings()
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_const.py", line 230, in get_makerbot_settings
    create_makerbot_settings()
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_const.py", line 212, in create_makerbot_settings
    create_makerbot_params(makerbot_settings)
  File "/home/top/dev/trading/pytomicDEX_makerbot/lib_const.py", line 118, in create_makerbot_params
    "bot_refresh_rate": int(order_refresh_rate)    
ValueError: invalid literal for int() with base 10: ''

```

**Comment by damascene** [comment]
Issue is that the application was not using a default value for not filled update interval `How often to update prices in seconds (e.g. 180): `

**Comment by smk762** [comment]
Thanks for the feedback! This should be resolved by https://github.com/smk762/pytomicDEX_makerbot/pull/6/commits/570f97300ba0c453f8d5b2a69eec702609d8dcf6
